### PR TITLE
Added C++ and Java Solution for leet code 82&2164 

### LINKED ISSUE #155: Count Bad Pairs Leet Code medium
Hey I want to add the solution for the above problem. 

Screenshot 2022-10-03 165636

### LINKED ISSUE #156: Seive Algorithms and its variations
**Hey I want to add up the above algorithms variation and their respective problems.
Please assign me that @Vanshika2063**

### PR DESCRIPTION
**Pull request by AbhishekCS3459**
**JAVA SOLUTION-->**

Screenshot 2022-10-03 183828

**C++ SOLUTION-->**

Screenshot 2022-10-03 183647

### CODE REVIEW

**Comment by AbhishekCS3459** [comment]
**Added Solution for Leet Code Question 82 -- > Remove Duplicates from Sorted Linked List (Java & C++)** @Vanshika2063

**Comment by AbhishekCS3459** [comment]
Added C++ Solution @Vanshika2063 
Screenshot 2022-10-03 191435
Added Java Solutio
Screenshot 2022-10-03 191928
n @Vanshika2063

**Comment by Vanshika2063** [comment]
remove SS, put your code in respective folder and rename it according to there question name

**Comment by AbhishekCS3459** [comment]
> remove SS, put your code in respective folder and rename it according to there question name

@Vanshika2063 **there is folder named medium, Should I Upload it there?? 
This time I had removed the ss of the questions as you mentioned above.**

**Comment by AbhishekCS3459** [comment]
@Vanshika2063  here is the pull request please review it

**Comment by Vanshika2063** [comment]
this is amazing @AbhishekCS3459 
thanks for the contribution in my repo and please share in social media and tag me on twitter

**Comment by AbhishekCS3459** [comment]
Hey does your repo has been excluded form the hacktoberfest as it is showing there..? @Vanshika2063

**Pull request merged**
